# Generated by Django 5.0.4 on 2024-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='None', max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='None', max_length=8),
        ),
    ]
