# Generated by Django 5.0.4 on 2024-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_rating_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
