# Generated by Django 5.0.4 on 2024-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_registraion_paper_vehicle_registration_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_paper',
            field=models.ImageField(blank=True, null=True, upload_to='registration_pics'),
        ),
    ]
