# Generated by Django 5.0.4 on 2024-04-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='v_auth_token',
        ),
    ]
