# Generated by Django 5.0.4 on 2024-04-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_vehicle_v_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_type', models.CharField(default='Car', max_length=4)),
                ('is_that_host', models.BooleanField(default=False)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dl_reg', models.CharField(max_length=20, unique=True)),
                ('dl_paper', models.ImageField(blank=True, null=True, upload_to='dl_pics')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
            ],
        ),
    ]
