# Generated by Django 5.0.4 on 2024-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_driver_dl_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_that_host',
            field=models.BooleanField(default=True),
        ),
    ]
