# Generated by Django 5.0.4 on 2024-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
