# Generated by Django 5.0.4 on 2024-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_ride_hosted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
