# Generated by Django 5.0.4 on 2024-04-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_profile_is_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='loc_address',
        ),
        migrations.AddField(
            model_name='ride',
            name='host_note',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider_note',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_host', to='website.profile'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to='website.profile'),
        ),
    ]
