# Generated by Django 5.0.4 on 2024-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_driver_host_alter_ride_hosted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_loc',
            field=models.CharField(max_length=40),
        ),
    ]
