# Generated by Django 5.0.4 on 2024-04-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_ride_destination_alter_ride_start_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=300),
        ),
    ]
