# Generated by Django 5.0.4 on 2024-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_location_distance_remove_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='riderpays',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
