# Generated by Django 5.0.4 on 2024-04-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
