# Generated by Django 5.0.4 on 2024-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_rename_is_host_profile_is_bike_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_loc',
            field=models.CharField(max_length=500),
        ),
    ]
