# Generated by Django 5.0.4 on 2024-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_ride_destination_alter_ride_start_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
