# Generated by Django 5.0.4 on 2024-04-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_ride_ride_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
